# Generated by Django 5.0.1 on 2026-05-04 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_entries', models.PositiveIntegerField(default=0, verbose_name='total entries')),
                ('scored_entries', models.PositiveIntegerField(default=0, verbose_name='scored entries')),
                ('progress_percentage', models.FloatField(default=0, verbose_name='progress percentage')),
                ('last_scored_at', models.DateTimeField(blank=True, null=True, verbose_name='last scored at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_progress', to='competitions.competition', verbose_name='competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_progress', to=settings.AUTH_USER_MODEL, verbose_name='judge')),
            ],
            options={
                'verbose_name': 'judge progress',
                'verbose_name_plural': 'judge progress',
                'ordering': ['-updated_at'],
                'unique_together': {('judge', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_weighted_score', models.FloatField(default=0, verbose_name='total weighted score')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='rank')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='competitions.competition', verbose_name='competition')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='competitions.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'leaderboard entry',
                'verbose_name_plural': 'leaderboard entries',
                'ordering': ['rank', '-total_weighted_score'],
                'indexes': [models.Index(fields=['competition', 'rank'], name='scoring_lea_competi_876fcb_idx'), models.Index(fields=['competition', '-total_weighted_score'], name='scoring_lea_competi_df7b14_idx')],
                'unique_together': {('competition', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_value', models.PositiveIntegerField(help_text='Score from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='score value')),
                ('weighted_score', models.FloatField(default=0, editable=False, verbose_name='weighted score')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.criteria', verbose_name='criteria')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.entry', verbose_name='entry')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='judge')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['judge', 'entry'], name='scoring_sco_judge_i_b652c9_idx'), models.Index(fields=['entry', 'criteria'], name='scoring_sco_entry_i_dd8699_idx')],
                'unique_together': {('judge', 'entry', 'criteria')},
            },
        ),
    ]
