# Generated by Django 5.0.1 on 2026-05-06 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.PositiveIntegerField(help_text='Score from 0 to 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='score value'),
        ),
    ]
