# Generated by Django 5.0.1 on 2026-05-08 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_score_0_to_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.PositiveIntegerField(help_text='Score from 0 to the competition max score', validators=[django.core.validators.MinValueValidator(0)], verbose_name='score value'),
        ),
    ]
