# Generated by Django 5.0.1 on 2026-05-04 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competitions/', verbose_name='competition image')),
                ('rules', models.TextField(blank=True, verbose_name='rules')),
                ('max_entries_per_participant', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max entries per participant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('weight', models.PositiveIntegerField(help_text='Weight from 1 to 5, where 5 is most important', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='weight')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='competitions.competition', verbose_name='competition')),
            ],
            options={
                'verbose_name': 'criterion',
                'verbose_name_plural': 'criteria',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('participant_name', models.CharField(max_length=255, verbose_name='participant name')),
                ('participant_email', models.EmailField(blank=True, max_length=254, verbose_name='participant email')),
                ('description', models.TextField(verbose_name='description')),
                ('file', models.FileField(blank=True, null=True, upload_to='entries/', verbose_name='file')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entries/images/', verbose_name='image')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition', verbose_name='competition')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_entries', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=20, verbose_name='status')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invited at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competition', verbose_name='competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='judge')),
            ],
            options={
                'verbose_name': 'judge assignment',
                'verbose_name_plural': 'judge assignments',
                'ordering': ['-invited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['-created_at'], name='competition_created_46cbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['status'], name='competition_status_065ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['created_by'], name='competition_created_a6ddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='criteria',
            index=models.Index(fields=['competition', 'order'], name='competition_competi_563950_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['competition', '-submitted_at'], name='competition_competi_da6e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_e39458_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['judge', 'status'], name='competition_judge_i_ce4392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('competition', 'judge')},
        ),
    ]
