# Generated by Django 5.0.1 on 2026-05-08 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_score',
            field=models.PositiveIntegerField(default=10, help_text='Maximum score a judge can give per criteria (e.g. 10 or 100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='max score per criteria'),
        ),
    ]
