# Generated by Django 5.0.1 on 2026-05-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='participant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='participant name'),
        ),
    ]
