# Generated by Django 5.0.1 on 2026-05-08 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_entry_description_alter_entry_participant_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingJudgeInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invited at')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to='competitions.competition', verbose_name='competition')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pending_invites', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
            ],
            options={
                'verbose_name': 'pending judge invite',
                'verbose_name_plural': 'pending judge invites',
                'unique_together': {('email', 'competition')},
            },
        ),
    ]
