# Generated by Django 5.2.14 on 2026-05-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_category_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='total_max_score',
            field=models.PositiveIntegerField(blank=True, help_text='The maximum total score an entry can receive (e.g. 100)', null=True, verbose_name='total maximum score'),
        ),
    ]
