# Generated by Django 5.2.14 on 2026-05-22 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_add_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='max_score',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='max score per criteria'),
        ),
    ]
