# Generated by Django 5.0.1 on 2026-05-04 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('notification_type', models.CharField(choices=[('judge_invite', 'Judge Invitation'), ('judge_accepted', 'Judge Accepted'), ('new_entry', 'New Entry'), ('competition_started', 'Competition Started'), ('competition_ended', 'Competition Ended'), ('scoring_complete', 'Scoring Complete'), ('general', 'General')], default='general', max_length=50, verbose_name='notification type')),
                ('related_object_id', models.CharField(blank=True, max_length=255, verbose_name='related object ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='related object type')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_sent_via_email', models.BooleanField(default=False, verbose_name='sent via email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
