# Generated by Django 5.2.14 on 2026-05-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('judge_invite', 'Judge Invitation'), ('judge_invited', 'Judge Invitation'), ('judge_accepted', 'Judge Accepted'), ('new_entry', 'New Entry'), ('competition_started', 'Competition Started'), ('competition_ended', 'Competition Ended'), ('scoring_complete', 'Scoring Complete'), ('general', 'General')], default='general', max_length=50, verbose_name='notification type'),
        ),
    ]
